#!/usr/bin/env bash
#
# Transfer a file from client to server

if (( $# < 3 ))
then
  printf 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY' "${0##*/}"
  exit 1

fi

if (($# < 4))
then
  scp -o 'StrictHostKeyChecking No' -- "$1" "$3@$2:"
else
  scp -o 'StrictHostKeyChecking No' -i "$4" -- "$1" "$3@$2:"
fi
